#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory


# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions


runApplication blockMesh
mv constant/polyMesh constant/fluid/polyMesh

runApplication $(getApplication)

echo
echo "creating files for paraview post-processing"
echo
paraFoam -touchAll

